In [45]:
import numpy as np
import random

In [140]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [141]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [142]:
c = b[::-1]
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [143]:
d = np.arange(0,9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [145]:
e = np.array([1,2,0,0,4,0])
print( np.where(e == 0))

(array([2, 3, 5], dtype=int64),)


In [146]:
f = np.random.random((30))
print(f.mean())

0.5388136871372177


In [147]:
g = np.ones(25).reshape(5,5)
g[1:-1,1:-1] = 0
print(g)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [148]:
h = np.ones (64).reshape(8,8)
h[1::2,::2] = 0
h[::2,1::2] = 0
print(h)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [149]:
ii = np.array([[0,1],[1,0]])
i =np.tile(ii,(4,4))
print(i)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [150]:
j = np.arange(11)
j[3:8] = j[3:8] * -1
print(j)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [151]:
k = np.random.random(10)
k.sort()
print(k)

[0.11771047 0.27316181 0.35584466 0.36771774 0.53732366 0.57620877
 0.6745813  0.78108362 0.90385355 0.94232244]


In [131]:
lA = np.random.randint(0,2,5)
lB= np.random.randint(0,2,5)

print(lA == lB)

[False  True  True False  True]


In [138]:
m = np.arange(10, dtype=np.int32)
print(m.dtype)
m = m.astype('float32')
print(m.dtype)

int32
float32


In [139]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diagonal(C)
print(D)

[ 18  66 132]
